<a href="https://colab.research.google.com/github/KrushnaTaur/ML-Practice/blob/main/01_Basics/05_NumPy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Introduction to NumPy Arrays

In [1]:
import numpy as np

In [2]:
# Create a simple list and convert to numpy array
list1 = [1, 2, 3, 4, 5]
arr1 = np.array(list1)
print("Array:", arr1)
print("Type:", type(arr1))

Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [3]:
# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


# 2. Creating Arrays (zeros, ones, arange, linspace)

In [15]:
a = np.zeros((2,3))
b = np.ones((3,3))
c = np.arange(1,10,2)
d = np.linspace(0,1,5)

print("Zeros:\n", a)
print("Ones:\n", b)
print("Arange:\n", c)
print("Linspace:\n", d)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arange:
 [1 3 5 7 9]
Linspace:
 [0.   0.25 0.5  0.75 1.  ]


# 3. Array Indexing & Slicing

In [10]:
arr = np.array([10,20,30,40,50,60,70])
print(arr[2])      # single element

30


In [11]:
print(arr[1:5])    # slicing

[20 30 40 50]


In [12]:
print(arr[-3:])    # from end

[50 60 70]


In [13]:
print(arr[::2])    # step slicing

[10 30 50 70]


In [14]:
arr[3] = 99        # modify
print("Modified:", arr)

Modified: [10 20 30 99 50 60 70]


# 4. Array Operations

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a + b)

Addition: [5 7 9]


In [17]:
print("Multiplication:", a * b)

Multiplication: [ 4 10 18]


In [18]:
print("Mean:", a.mean())

Mean: 2.0


In [19]:
print("Reshape:", np.arange(1,10).reshape(3,3))

Reshape: [[1 2 3]
 [4 5 6]
 [7 8 9]]


#5. Mathematical Functions

In [20]:
arr = np.array([4,9,16,25])

In [21]:
print("Sqrt:", np.sqrt(arr))

Sqrt: [2. 3. 4. 5.]


In [22]:
print("Sum:", np.sum(arr))

Sum: 54


In [23]:
print("Dot Product:", np.dot([1,2],[3,4]))

Dot Product: 11


In [24]:
print("Exp:", np.exp(arr))

Exp: [5.45981500e+01 8.10308393e+03 8.88611052e+06 7.20048993e+10]


# 6. Random Numbers with np.random

In [25]:
print("Random int 0–10:", np.random.randint(0,10,5))

Random int 0–10: [7 5 8 4 8]


In [26]:
print("Random float:", np.random.rand(3))

Random float: [0.37670832 0.26091253 0.34449995]


In [27]:
print("Random 2D Array:\n", np.random.randn(3,3))

Random 2D Array:
 [[-0.13598012  0.14658106 -0.50808786]
 [-0.68791824  0.8806284   0.39949804]
 [-0.04993975  0.12857629 -0.04049565]]


# 7. NumPy Practice Problems

Create and Inspect

In [28]:
arr = np.arange(10, 55, 5)

In [29]:
print("Array:", arr)

Array: [10 15 20 25 30 35 40 45 50]


In [30]:
print("Shape:", arr.shape)

Shape: (9,)


In [31]:
print("Dimensions:", arr.ndim)

Dimensions: 1


In [32]:
print("Data Type:", arr.dtype)

Data Type: int64


Reshape Practice

In [33]:
arr = np.arange(1, 13).reshape(3, 4)

In [34]:
print("3x4 Array:\n", arr)

3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
print("2nd Row:", arr[1])

2nd Row: [5 6 7 8]


In [36]:
print("Element at row 3, column 2:", arr[2, 1])

Element at row 3, column 2: 10


Operations

In [37]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [38]:
print("Addition:", a + b)

Addition: [5 7 9]


In [39]:
print("Multiplication:", a * b)

Multiplication: [ 4 10 18]


In [40]:
print("Mean of a:", a.mean())

Mean of a: 2.0


In [41]:
print("Mean of b:", b.mean())

Mean of b: 5.0


Boolean Filtering

In [42]:
arr = np.arange(1, 16)
even_nums = arr[arr % 2 == 0]
print("Even numbers:", even_nums)

Even numbers: [ 2  4  6  8 10 12 14]


Random Array

In [43]:
rand_arr = np.random.randint(1, 21, (3, 3))
print("Random 3x3 Matrix:\n", rand_arr)

Random 3x3 Matrix:
 [[ 2 13 13]
 [ 8  4  5]
 [ 6  2  3]]


In [44]:
print("Max:", rand_arr.max())

Max: 13


In [45]:
print("Min:", rand_arr.min())

Min: 2


In [46]:
print("Sum:", rand_arr.sum())

Sum: 56


Slicing Challenge

In [47]:
arr = np.arange(10, 110, 10)
print("Array:", arr)

Array: [ 10  20  30  40  50  60  70  80  90 100]


In [48]:
print("Every 2nd element:", arr[::2])

Every 2nd element: [10 30 50 70 90]


In [49]:
print("Last 3 elements:", arr[-3:])

Last 3 elements: [ 80  90 100]


In [50]:
print("Reverse order:", arr[::-1])

Reverse order: [100  90  80  70  60  50  40  30  20  10]


Matrix Math

In [51]:
A = np.array([[2, 3],
              [4, 5]])
B = np.array([[1, 0],
              [7, 2]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[2 3]
 [4 5]]
Matrix B:
 [[1 0]
 [7 2]]


In [52]:
print("Addition:\n", A + B)

Addition:
 [[ 3  3]
 [11  7]]


In [53]:
print("Dot Product:\n", np.dot(A, B))

Dot Product:
 [[23  6]
 [39 10]]


In [54]:
print("Transpose of Dot Product:\n", np.dot(A, B).T)

Transpose of Dot Product:
 [[23 39]
 [ 6 10]]


Statistical Ops

In [55]:
arr = np.random.randint(1, 51, 10)
print("Array:", arr)

Array: [45 21 35 30 36 39 27 31 12  2]


In [56]:
print("Mean:", np.mean(arr))

Mean: 27.8


In [57]:
print("Median:", np.median(arr))

Median: 30.5


In [58]:
print("Standard Deviation:", np.std(arr))

Standard Deviation: 12.319090875547595


Unique & Frequency

In [59]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5, 6])
unique, counts = np.unique(arr, return_counts=True)

In [60]:
print("Unique Elements:", unique)

Unique Elements: [1 2 3 4 5 6]


In [61]:
print("Frequency Count:", counts)

Frequency Count: [1 2 1 3 2 1]


Advanced Mini Task

In [62]:
arr = np.random.randint(0, 10, (4, 4))
print("Original Array:\n", arr)

Original Array:
 [[5 7 4 4]
 [8 8 4 2]
 [6 0 0 3]
 [2 9 6 5]]


In [63]:
# Replace evens with 0, odds with 1
binary = np.where(arr % 2 == 0, 0, 1)
print("Binary Array:\n", binary)

Binary Array:
 [[1 1 0 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 0 1]]
